# Generated by Django 4.2 on 2023-08-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_article_likes_remove_comment_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date_article_changed',
            new_name='date_article_created',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='date_created',
            new_name='date_changed',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_article_changed',
            new_name='date_article_created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_created',
            new_name='date_changed',
        ),
    ]
