# Generated by Django 4.2 on 2023-08-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='file_db/user_avatars/default/def_avatar.jpg', upload_to='file_db/user_avatars'),
        ),
    ]
