# Generated by Django 4.2 on 2023-08-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='static/user-avatars/def_avatar.jpg', upload_to='static/user-avatars'),
        ),
    ]
